cache:
  paths:
  - node_modules/
  - .ipfs/
stages:
- test
- build
- deploy
test_dummy:
  image: node:8.11.4
  stage: test
  before_script:
  - npm install
  script:
  - npm run test
build_site:
  image: node:8.11.4
  stage: build
  before_script:
  - npm install
  script:
  - npm run build
  artifacts:
    paths:
    - build
    expire_in: 20 minutes
deploy_ipfs:
  image: jbenet/go-ipfs:master
  stage: deploy
  before_script:
  - ipfs init
  script:
  - ipfs add -r build/
  - ipfs add --only-hash -r build | tail -n 1 | awk '{ print $2 }' | ipfs name publish
  only:
  - master
